#File Tree structure

setenv DV_TOOL_VERSION    1.0.0
setenv DV_TOOL_ROOT       ./dv_scripts
setenv BAR_CMD            bar
setenv RGR_CMD            rgr
setenv DV_BAR_ROOT        $DV_TOOL_ROOT/${BAR_CMD}
setenv DV_RGR_TOOT        $DV_TOOL_ROOT/${RGR_CMD}


### ./BAR/
./VERSION           # Version number file (like 1.0.0.0)
./doc               # documentations

./bin               # Soft links to scripts executables, or new scripts

./flows             # main flow scripts (.mk for each target)
./flows/help*       # list out the mk tgts
        help_emu/hlv/aldec/jasper/vc_formal/qbuild.txt
        
 #---------------------------
 # Main makefiles
 #---------------------------
  template.mk 
  qbar.mk
    #1. include common.mk, sub dir
    ./include/common.mk   # call gmsl, define common mk variables like SHELL/VERBOSITY/QUIET ...
    ./include/gmsl        # wrapper of __gmsl by using ifndef/define/endif to avoid of duplicated call
    ./include/__gmsl      # GNU Make Standard Lib, version := 1.1.5
    #2. include util/query.mk: ifeq MAKECMDGOALS,__query_info
    utility.mk            # defines UTILITY_TARGETS and genreate REBUILD
    query.mk              # _query_info tgt: echo $BAR_DRM_RES* vars
    #3. call $FLOW makes (FLOW=formal/sim/emu)
    emu.mk                # FLOW=emu
    jasper.mk             # ifreq $FLOW_${FORMAL}=formal_jg
    vc_formal.mk          # ifreq $FLOW_${FORMAL}=formal_vc_formal
    #4. call macro.mk
    macro.mk              # function macro defines like: 
                          #   __comp_lock/unlock, _killer_comp_lock/unlock
                          #   __open/close_task,
                          #   __cmd_start/done_fail, __open/close/update_rebar_scripts
    #5. legacy hlv flow
    hlverif_legacy_vars_mapping.mk  # map legacy HLV_* variables to new vars (remove HLV_ prefix)
    compatibility.mk      # define __TO_BE_DEPRECATED_VARS, __DEPRECATED_VARS and print it
    
    #6. tool/lib
    tools.mk              # Two key vars (FLOW, HW_ENABLE) decide HDL compiler (set default SIM=modelsim, COMPILE_VERDI=0)
    common_lib.mk         # ifeq __ENABLE_TTE_FLOW,00
    
    #7. abv/hdl/dut
    abv_libs.mk
    abv.mk
    
    hdl.mk
    dut_libs.mk           # ifeq __ENABLE_TTE_FLOW,00
    dut.mk
      include upf.mk
    elab_dut.mk

    #8. elab th/hvl/tb/
    th.mk
    hvl.mk
    
    tb_lib.mk
    tb.mk
    test.mk
    tb_doc.mk
    tb_lint.mk
           
    sandbox_ide.mk       # ifeq __ENABLE_TTE_FLOW,00
    
    sim_top.mk
    
    ./helpers/ (*.mk)     # helpers for xcelium XRUN mode 3-steps
    
    aldec.mk              # ifeq __ENABLE_ALDEC_FLOW,1
    synopsys.mk           # ifeq __ENABLE_SYNOPSYS,1

    misc.mk               # ifeq HVLLINK_IN_DUT,0
    elab.mk
    
    design_dump_info.mk
    
    hvl_link.mk           # if EMULATION_PRE_JOB,1
    hvl_link_indut.mk     # elif HVLLINK_IN_DUT,1
    
    misc.mk               # if HVLLINK_IN_DUT,1
    hlverif.mk            # if __ENABLE_HLV_FLOW,1
    
    sim.mk
    prove.mk
    debug.mk              # if __ENABLE_HLV_FLOW,1
    app.mk
    coverage.mk
    ice.mk                # if __ENABLE_TTE_FLOW,00
    fsim.mk
    vcs_unr.mk
    covercheck.mk
    pwrest.mk             # ifneq $PWR_CALCULATOR,''
    
    vip_stats.mk          # if $ENABLE_VIP_STATS
    
    include $(BAR_INIT_MK)  # generated by previous tgt
    
    include $BAR_MK_POST_INCLUDES   # ifneq BAR_MK_POST_INCLUDES,''
      
 
./scripts           # Wrapper/top level scripts based on libs
  ./internal/       # internal perl scripts
                
                 
./template
  ./common/
  ./certitude/
  ./certe/
  ./doxygen/
  ./dvm/
  ./dvt/
  ./emu/
  ./hlv/
  ./ifv/
  ./ius/
  ./jasper/
  ./modelsim/
  ./mvsim/
  ./novas/
  ./ntb/
  ./palladium/
  ./powerpro/
  ./qbuild/
  ./tbx/
  ./user_scripts/
  ./uvm/
  ./vc_apps/
  ./vc_formal/
  ./vcs_mx/
  ./vcs_pure/
  ./veloce/
  ./verdi/

./wrappers  (*.pm)
  Vcs_mx.pm
  Verdi.pm

./perllib          # standalone/shared/utils perl libs for lib/scripts
  ./GATE_ID/PD_bundle_json.pm
  ./GATE_ID/pre_process_MK_gate.pm
  ./GATE_ID/process_HM_libs.pm
  ./GATE_ID/process_sdf.pm
  ./dvm/
  ./emu/
  ./formal/
  ./hlv/
  ./bar/
    ./cs2flow/
  ./qbuild/
  ./qpb/IPC/
  ./vc_app/

./python_lib       # standalone/shared/utils py libs for lib/scripts


./lib               # libs for scripts, or .so/.a libs
./lib/linux
./lib/solaris
